# install unofficial firefox nightly & firefox dev flatpak remote & packages from https://firefox-flatpak.mojefedora.cz/

   - name: Add the org.mozilla.FirefoxRepo flatpak repository remote to the system installation
     flatpak_remote:
       name: org.mozilla.FirefoxRepo
       state: present
       flatpakrepo_url: https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo
       
   - name: Install the Firefox nightly flatpak from the org.mozilla.Firefox remote system-wide
     flatpak:
       name: org.mozilla.FirefoxNightly
       state: present
       remote: org.mozilla.FirefoxRepo
      
   - name: Install the Firefox nightly flatpak from the org.mozilla.Firefox remote system-wide
     flatpak:
       name: org.mozilla.FirefoxDevEdition
       state: present
       remote: org.mozilla.FirefoxRepo
