# install unofficial firefox nightly & firefox dev flatpak remote & packages from https://firefox-flatpak.mojefedora.cz/

   - name: Add the org.mozilla.FirefoxRepo flatpak repository remote to the system installation
     flatpak_remote:
       name: org.mozilla.FirefoxRepo
       state: present
       flatpakrepo_url: https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo      
       
   - name: Install flatpak packages from the org.mozilla.FirefoxRepo remote system-wide
     flatpak: name={{item}}
     remote: org.mozilla.FirefoxRepo
     with_items:
       - org.mozilla.FirefoxDevEdition
