#install gnome and gnome-nightly remotes and runtimes

   - name: Add the Gnome flatpak remote to the system installation
     flatpak_remote:
       name: gnome
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

   - name: Add the Gnome runtimes flatpak remote to the system installation
     flatpak_remote:
       name: gnome
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome.flatpakrepo

   - name: Add the gnome-nightly flatpak repository remote to the system installation
     flatpak_remote:
       name: gnome-nightly
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome-nightly.flatpakrepo
