#install local rpm packages

- name: Install Local Packages        
     tags: foo                          
     shell: |                           
      rpm-ostree install --idempotent \
      libdvdcss-1.4.2-1.fc28.remi.x86_64 \
      rpmfusion-free-release-28-1.noarch  \
      rpmfusion-nonfree-release-28-1.noarch

