# install firefox nightly & firefox dev flatpak remote & packages. See https://firefox-flatpak.mojefedora.cz/

---

   - name: Add the Gnome flatpak remote to the system installation
     flatpak_remote:
       name: gnome
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

   - name: Add the Gnome runtimes flatpak remote to the system installation
     flatpak_remote:
       name: gnome
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome.flatpakrepo

   - name: Add the gnome-nightly flatpak repository remote to the system installation
     flatpak_remote:
       name: gnome-nightly
       state: present
       flatpakrepo_url: https://sdk.gnome.org/gnome-nightly.flatpakrepo

   - name: Add the org.mozilla.FirefoxRepo flatpak repository remote to the system installation
     flatpak_remote:
       name: org.mozilla.FirefoxRepo
       state: present
       flatpakrepo_url: https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo

   - name: Install flatpak packages from the org.mozilla.FirefoxRepo remote system-wide
     flatpak: name={{item}}
     with_items:
      - org.mozilla.FirefoxDevEdition
      - org.mozilla.FirefoxNightly
     state: present
     remote: org.mozilla.FirefoxRepo
     
     
