# install remote rpm packages

- name: Install Remote Packages        
  tags: foo                          
  shell: |                           
    rpm-ostree install --idempotent \
    arc-theme \
    chrome-gnome-shell \
    chromium \
    chromium-libs-media-freeworld\
    gnome-tweaks \
    gstreamer1-libav \
    dropbox \
    nautilus-dropbox \
    ffmpeg \
    gnome-tweaks \
    gnome-weather \
    youtube-dl  
