# install local rpm packages

- name: Install Local Packages        
  tags: foo                          
  shell: |                           
    rpm-ostree install --idempotent \ 
    
  args: 
     chdir: /var/home/john/Downloads 
